name: BungeecordAutoConfig
version: ${project.version}
main: de.epsdev.bungeeautoserver.spigottest.Bungeeautoserver.BungeecordAutoConfig
commands:
  changeServer:
    description: Change your or another players current server.
    permission: bungee.changeserver

  changeInstance:
    description: Change your or another players current server to a specific instance.
    permission: bungee.changeserver

  getServerInfo:
    description: Returns information about a specific server type.
    permission: bungee.status

  closeserver:
    description: Closes the active server instance.
    permission: bungee.opencloseserver

  openserver:
    description: Opens the active server instance.
    permission: bungee.opencloseserver

  broadcast:
    description: Send an message to all active instances.
    permission: bungee.broadcast

  menu:
    aliases:
      - server
      - m
    description: Opens a server selection GUI